site_name: Apunts d'en Joan Pardo per DigiTechFP
site_description: Publicació progressiva des d'un sol repositori
site_url: https://jpardo20.github.io/apunts-jpardo20/

docs_dir: docs
site_dir: site

nav:

  - Mòduls de SMX:
    - 0221 Muntatge i manteniment d’equips moduls:
      # - Presentacions:
        - Presentacions:  presentacions/?modul=0221-muntatge-i-manteniment-d-equips
      # - Activitats:
      #   - Activitat mim-ud01-ae01: moduls/0221-muntatge-i-manteniment-d-equips/presentacions/mim-ud01-ae01.reveal
    - 0223 Aplicacions ofimàtiques:
      # - Presentacions:
        - Presentacions:  presentacions/?modul=0223-aplicacions-ofimatiques
    - 0225 Xarxes locals:
      # - Presentacions:
        - Presentacions:  presentacions/?modul=0225-xarxes-locals
    - MOPT1 Programació Python:
      # - Presentacions:
        - Presentacions:  presentacions/?modul=mopt1-robotica-python
    - PR2T - Projecte 2n trimestre:
      # - Presentacions:
        - Presentacions:  presentacions/?modul=1rsmx-proj-2n-trim
    - Tutoria:
      # - Presentacions:
        - Presentacions:  presentacions/?modul=tutoria
  - Mòduls de DAM:
    - 0373 - Llenguatges de marques:
      # - Presentacions:
        - Presentacions:  presentacions/?modul=0373-llenguatges-de-marques
    - 0484 - Bases de dades:
      # - Presentacions:
        - Presentacions:  presentacions/?modul=0484-bases-de-dades
    - 0483 - Sistemes Informàtics:
      # - Presentacions:
        - Presentacions:  presentacions/?modul=0483-sistemes-informatics
    - PRTR - Projecte transversal:
      # - Presentacions:
        - Presentacions:  presentacions/?modul=1rdam-pro-dam-transversal
    - Tutoria:
      # - Presentacions:
        - Presentacions:  presentacions/?modul=tutoria
  # - <h3>Mòduls de DAM</h3>:
  
  #   - 0373 - Llenguatges de marques:
  #       - Resultats d'Aprenentatge (RA): 
  #         - apunts: moduls/0373-llenguatges-de-marques/apunts/index.html
  #       - Presentacions:
  #         - Presentacions:  presentacions/?modul=0373-llenguatges-de-marques

  
theme:
  name: material
  custom_dir: overrides
  logo: assets/img/VERT-01-SIN-CAJA-BLANCO-RGB@2x-768x593.png
  favicon: assets/img/cropped-cropped-VERT-01-BLANCO-RGB-copia-150x150.png
  features:
    - navigation.indexes
    - navigation.sections
    
  revealjs:
    history: true
    slideNumber: true

extra_css:
  - assets/css/styles.css
  - assets/css/base.css
  - assets/css/tema.css
  - assets/css/fonts.css
  - assets/css/header.css

extra_javascript:
  - assets/js/presentador.js
  
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - tables
  - toc:
      permalink: true
